---
title: "Phase 1a MLM"
author: "Jenny Terry"
date: "12/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)
library(magrittr)
library(ggplot2)
```

First, read in the cleaned, anonymised data.

```{r import_data}
# read in anonymised data file
statanx_data <- readr::read_csv(here::here("data", "anon_data.csv"))

# check first few rows
head(statanx_data)
```
Next, create the composite scores required for this analysis - stars, rmars, and each of the STICSA scales (trait, pre-state, post-state).

```{r composite_scores}
# create composite scores

# stars mean
statanx_data <- statanx_data %>% dplyr::mutate(stars = rowMeans(dplyr::select(., dplyr::starts_with("q4.1")), na.rm = TRUE))

# rmars mean
statanx_data <- statanx_data %>% dplyr::mutate(rmars = rowMeans(dplyr::select(., dplyr::starts_with("q4.3")), na.rm = TRUE))

# sticsa trait mean
statanx_data <- statanx_data %>% dplyr::mutate(trait = rowMeans(dplyr::select(., dplyr::starts_with("q5.1")), na.rm = TRUE))

# sticsa pre-state mean
statanx_data <- statanx_data %>% dplyr::mutate(pre_state = rowMeans(dplyr::select(., dplyr::starts_with("q5.2")), na.rm = TRUE))

# sticsa post-state mean
statanx_data <- statanx_data %>% dplyr::mutate(post_state = rowMeans(dplyr::select(., dplyr::starts_with("q8.1")), na.rm = TRUE))
```

```{r select_vars}
# select variables that we'll be using in this analysis
mlm_data <- dplyr::select(statanx_data, id, stars, rmars, trait, pre_state, post_state, mcq)

# check first few rows
head(mlm_data)
```

```{r check_missing}
# check missing data per variable
mlm_data %>% 
  dplyr::summarise_each(list(~sum(is.na(.)))) %>%
  tidyr::gather()
```

```{r standardise_subj_anx}
# standardise maths anxiety and stats anxiety (mean = 0, sd = 1)
mlm_data$stars <- scale(mlm_data$stars)
mlm_data$rmars <- scale(mlm_data$rmars)
```

```{r convert_long}
# convert wide to long
long_data <- mlm_data %>% tidyr::pivot_longer(cols = c("pre_state", "post_state"), names_to = "time", values_to = "state_anx")

# check first few rows
head(long_data)
```

```{r covert_factors}
# convert character variables to factors
long_data$mcq <- factor(long_data$mcq)
long_data$id <- factor(long_data$id)

# create numerical time variable
long_data %<>% dplyr::mutate(
  time_num = ifelse(time == "pre_state", 0, 1)
)
```

```{r centre_trait}
# group mean centre level 1 continuous predictors
long_data <- long_data %>%
    dplyr::group_by(id) %>%
    dplyr::mutate(gmc_trait = mean(trait, na.rm = TRUE))
```

Check normality of intercepts and slopes.

```{r normality}
# check assumption of normality of intercepts and slopes for level 1 predictors

# run a regression for each individual                 ###THIS CODE STILL NEEDS FIXING!###
#ind_reg <- long_data %>% 
  #dplyr::group_by(id) %>% 
  #dplyr::do(model = lm(state_anx ~ time_num, .))

# frequency polygon of the intercepts
#ind_reg %>% broom::tidy(model) %>% filter(term == "(Intercept)") %>% 
  #ggplot(aes(estimate))
  #geom_freqpoly(binwidth = 0.5, size = 1) + 
  #xlab("Intercepts")

# frequency polygon of the slopes
#ind_reg %>% broom::tidy(model) %>% filter(term == "time_num") %>%
  #ggplot(aes(estimate)) + 
  #geom_freqpoly(binwidth = 0.5, size = 1) +
  #xlab("Slopes")
```

```{r unconditional_means}
mod_a <- lmerTest::lmer(state_anx ~ 1 + (1|id), long_data, REML = FALSE)
summary(mod_a)
lme4::confint.merMod(mod_a)
```

```{r unconditional_growth}
mod_b <- lmerTest::lmer(state_anx ~ time_num + (1|id), long_data, REML = FALSE)
summary(mod_b)
lme4::confint.merMod(mod_b)
```

Fit interaction model for eq. 1 (see pre-reg):

```{r interaction_eq1_a}
mod_c <- lmerTest::lmer(state_anx ~ gmc_trait + time_num*mcq*stars + (1|id) + (0 + time_num|id), long_data, REML = FALSE)
summary(mod_c)
lme4::confint.merMod(mod_c)
```

Fit interaction model for eq. 2 (see pre-reg):

```{r interaction_eq2}
mod_d <- lmerTest::lmer(state_anx ~ gmc_trait + time_num*mcq*rmars + (1|id) + (0 + time_num|id), long_data, REML = FALSE)
summary(mod_d)
lme4::confint.merMod(mod_d)
```

Create plots for poster: 

```{r plot_prep}
# rename vars for plots ('cos this is much easier than trying to change facet labels when using sjPlot!)
long_data %<>% dplyr::rename(statistics_anxiety = stars,
                                maths_anxiety = rmars)

#re-run models
mod_c_plot <- lmerTest::lmer(state_anx ~ gmc_trait + time_num*mcq*statistics_anxiety + (1|id) + (0 + time_num|id), long_data, REML = FALSE)

mod_d_plot <- lmerTest::lmer(state_anx ~ gmc_trait + time_num*mcq*maths_anxiety + (1|id) + (0 + time_num|id), long_data, REML = FALSE)
```

```{r plots}
sjPlot::plot_model(mod_c_plot, type = "pred", terms = c("time_num", "mcq", "statistics_anxiety")) +
  coord_cartesian(ylim = c(1, 4)) +
  scale_y_continuous(breaks = seq(1, 4, 0.5)) +
  scale_x_continuous(breaks = c(0, 1), labels = c("Pre", "Post")) +
  scale_colour_manual(values = c("#ffa500", "#2462E5"), name = "MCQ condition") +
  scale_fill_manual(values = c("#ffa500", "#2462E5"), name = "MCQ condition") +
  labs(x = "Time", y = "State anxiety (mean, range 1:4)", colour = "MCQ condition", title = "Predicted mean values of state anxiety change at different levels of \nSTATISTICS ANXIETY for each MCQ condition") +
  theme(strip.background = element_rect(fill = "#138d5f"), strip.text.x = element_text(size = 10, color = "white"))
  
  
sjPlot::plot_model(mod_d_plot, type = "pred", terms = c("time_num", "mcq", "maths_anxiety")) +
  coord_cartesian(ylim = c(1, 4)) +
  scale_y_continuous(breaks = seq(1, 4, 0.5)) +
  scale_x_continuous(breaks = c(0, 1), labels = c("Pre", "Post")) +
  scale_colour_manual(values = c("#ffa500", "#2462E5"), name = "MCQ condition") +
  scale_fill_manual(values = c("#ffa500", "#2462E5"), name = "MCQ condition") +
  labs(x = "Time", y = "State anxiety (mean, range 1:4)", colour = "MCQ condition", title = "Predicted mean values of state anxiety change at different levels of \nMATHS ANXIETY for each MCQ condition") +
  theme(strip.background = element_rect(fill = "#138d5f"), strip.text.x = element_text(size = 10, color = "white"))
```



